# SPDX-FileCopyrightText: 2019-2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: Unlicense

# Exclusion parameters.
exclusions:
  # POSIX extended regular expressions that match external references
  # that have to be ignored (not verified).
  ignoreExternalRefsTo:
    # Note: For some reason, running `curl -I https://opensource.org/licenses/MIT` from within
    # a GitHub Action's agent returns a 503.
    # For this reason, we're temporarily disabling this check.
    - https://opensource.org/licenses/MIT

# Parameters of scanners for various file types.
scanners:

  markdown:
    # Flavor of markdown, e.g. GitHub-flavor.
    #
    # This affects which anchors are generated for headers.
    flavor: GitHub
